### ISSUE TITLE
The Desk tool crashed: Error: Cannot resolve a DOM node from Slate node

### ISSUE THREAD

**Issue by robksawyer** [ndimatteo/HULL#118]
Note: I'm new to Sanity, so I'm sure it's something weird that I did. However, I'm so new that I have no idea what to look for. 

Any ideas? I opened an issue over at https://github.com/sanity-io/sanity/issues/4204

**Comment by ndimatteo** [comment]
Hey there @robksawyer, this sounds more like an issue with Sanity's Portable Text editor (Slate) and malformed data that it's having trouble parsing. This can happen when content is copy/pasted that has artifacts that affect how Slate handles parsing said content. It could also be something to do with your `initialValue` data.

Either way, I don't believe this is a HULL-specific issue, so I'm going to close this for now, but feel free to open it again if you or the Sanity team uncover something to indicate otherwise! 🤘

**Comment by robksawyer** [comment]
@ndimatteo thanks for the info. I'll try to see if there are any rogue characters or something in the data.
