### ISSUE TITLE
Sanity not connecting to Storefront

### ISSUE THREAD

**Issue by Elko-Lemiso** [ndimatteo/HULL#123]
Hey folks, 

So I am having a bit of an issue with the storefront.

This is the error I get on the landing page.
"Home Page" is not set in Sanity, or the page data is missing.

When I check in the sanity studio, I dont see any content either, 
I followed the directions pretty well,
Anyone faced anything similar.
Would really appreciate the help. 

Cheers

**Comment by VikSinghDev** [comment]
Hey,

If you see that error, then you have setup correctly so far.

In order to render the home page, you need to load the sanity studio and configure the page settings, header, footer and some other info. Go through the studio settings thoroughly and you will be able to figure out the bare minimum to render the home page. Keep in mind, there are other studio settings you may need to configure to setup additional pages or functionality like the email sign ups. 

Hope this helps.

**Comment by dillytitan** [comment]
I had this issue before as well. I was able to to fix by using the below line to import any missing template files. 

`sanity dataset import ../.sanity-template/data/production.tar.gz --missing`
