### ISSUE TITLE
Can't locate Sanity Starter

### ISSUE THREAD

**Issue by j2is** [ndimatteo/HULL#132]
I might have missed it but I couldn't see this on the list of starter projects on Sanity?

**Comment by ndimatteo** [comment]
Hey there @j2is! Sanity has since revamped their website, incluidng their "templates" resources. Since HULL is still on V2 of the Sanity Studio, it's likely they removed it as a featured repo.

In the new year I have plans to revamp and update HULL, which will include upgrading to V3 of the Sanity Studio, and integrating with the [Sanity Connect](https://apps.shopify.com/sanity-connect) Shopify app.
