### ISSUE TITLE
Why are there no explicit product created webhook?

### ISSUE THREAD

**Issue by sbrerup** [ndimatteo/HULL#17]
Great repo.

I only see update and delete in the setup guide. Will update trigger on create as well?

**Comment by ndimatteo** [comment]
Thanks @sbrerup, and great question!

Yes, (last I checked) the Shopify API triggers the `product update` event even on product creation. And since both events use the same response, as noted [here](https://shopify.dev/docs/admin-api/rest/reference/events/webhook) in the Shopify API Docs, we only need to write _one_ API endpoint (our `/api/shopify/product-update`).

That all being said, there's no harm in adding a 3rd webhook in the Shopify Notifications settings for `product creation`. Simply use the same API endpoint as the `product update` one, and you should be all set!

**Comment by ndimatteo** [comment]
Good catch @sbrerup !

So yes, go ahead and add a 3rd webhook for `product creation` using the same URL for the `product update` webhook and you should be all set.

I'll update this in the HULL docs as well!

**Comment by ndimatteo** [comment]
This is updated :)
