### ISSUE TITLE
Other meta fields not included

### ISSUE THREAD

**Issue by dnlmzw** [ndimatteo/HULL#18]
Hi there,

Thanks again for the good work.

I was curious to know why only some fields on a product are not stored in Sanity? For example I need to retrieve things such as "Product type", "Tags" and "Collections" from Shopify.

As far as I can tell it's not possible to retrieve it via the [metafields.json](https://shopify.dev/docs/admin-api/rest/reference/metafield) but I can see that it does come up when I request [product.json](https://shopify.dev/docs/admin-api/rest/reference/products/product)

Do you have any thoughts on why you're not using the other endpoint, and can shine a light on what trouble I might potentially face by changing the endpoint?

**Comment by dnlmzw** [comment]
Yes, and description (`body_html` in products.json) also isn't being sent over, which would be nice.

**Comment by ndimatteo** [comment]
Hey there @dnlmzw,

Great question! The reason we are only sync'ing certain information from Shopify is because we're only using Shopify for the checkout process, so we only grab the bare minimum from Shopify needed for that.

The idea is that everything else, especially from a visual standpoint, should be handled through Sanity and your headless setup. This creates a clear delineation between what is handled on Shopify's side of things, and what is handled from the Sanity side of things.

You can think of Shopify as where you define your products (name, slug, price, variants, and quantity), and everything else (photos, descriptions, SEO, etc) is handled through Sanity.

Additionally, we are only using the `metafields.json` API to check if a sync needs to happen (using `jsondiff` to determine if a core data piece has changed between the last sync and the current change). We actually rely on the Shopify webhook response data to extract the data we need. Using this, instead of creating an additional API call to `products.json`, reduces the number of API calls as well. Which is important in keeping costs down and limits the risk of hitting the Shopify API limits.

So to your last point, you wouldn't want to change the API endpoint where we use the `metafields.json` as that's integral to determining if we should trigger a sync into Sanity (aka - hitting the Sanity API).

If you wanted to sync additional information from Shopify, you can check out what's sent with the webhook [here](https://shopify.dev/docs/admin-api/rest/reference/events/webhook), but I'd suggest keeping things like collections and tags on the Sanity side of things. You'll have a lot more flexibility to extend functionality that way, and from a Content editing standpoint it reinforces what each platform is used for (which should help keep confusion down for client's and their content/marketing teams).

I hope that helps!

**Comment by dnlmzw** [comment]
Thanks! I was heading down that route as well, but I wanted to check first what my options were. Thanks a lot for clarifying :)
