### ISSUE TITLE
Documentation: Sanity projectId needs to be changed

### ISSUE THREAD

**Issue by dnlmzw** [ndimatteo/HULL#46]
Hi,

I scratched my head a bit over this one.

Couldn't find anywhere in the documentation where it said that the `projectId` in `sanity.json` needed to be changed, so couldn't understand why I was locked out of sanity locally but not on my live environment.

No easy way of having an .env variable in the .json file I assume?

**Comment by ndimatteo** [comment]
hey there @dnlmzw! Yea, unfortunately Sanity doesn't have a dynamic config file currently 😞 

Me and a few others have suggested this improvement so that things like the `projectId` can be dynamically loaded in there from an `env` file.

In the meantime, I'll add a note about this in the readme, thanks for reminding me!
