### ISSUE TITLE
Cannot develop locally although app running on vercel

### ISSUE THREAD

**Issue by dev-rroslan** [ndimatteo/HULL#70]
hi, I clone https://github.com/ndimatteo/HULL.git and deploy on  sanity. The apps is running OK on vercel. However I cannot run it locally for development. I get this error: error - Failed to load next.config.js, I have tried using node 12.x, 14.x, 16.x but I get same error. When I run vercel env pull, I get this error: Error! The Secret "sec_nMOI8Xhg6lD5DndLXHpcdPDM" is not decryptable. I am new and I hope someone knows how to help me fix this.

I run it like this and it builds: vercel -e NODE_ENV=development -e SECRET=sec_nMOI8Xhg6lD5DndLXHpcdPDM

**Comment by ndimatteo** [comment]
Hey there @dev-rroslan, it's hard to say from your notes what the problem is, but it sounds like you've modified the dev/build scripts heavily. Please try using the default development and build scripts, and put `env` variables in a `.env` file.

Steps for all of this are outlined in the readme file as well, I'd suggest following along there first to get everything up and running both locally and through Vercel.
