### ISSUE TITLE
Wondering how to achieve this

### ISSUE THREAD

**Issue by geniti** [ndimatteo/HULL#72]
see image for reference 

I want to have de categories/collection/menu appear as swiper menu below header.

What is the best approach to achieve this
![Schermafbeelding 2022-01-12 om 13 37 03](https://user-images.githubusercontent.com/32541489/149141543-f46068b1-e5c0-4353-bbc8-bfaf74db7992.png)
?

**Comment by ndimatteo** [comment]
Hey there,

Lots of ways to do this, but one that comes to mind:

You could add a `menu` reference to your `collection` page content array modules.

That way you could create a menu of links to each collection, and simply reference it in your collection page content modules.

You'd obviously have to build out this new module based on that menu data, but should be pretty straight forward!

**Comment by geniti** [comment]
Thank for your reply, I was thinking bit the same way.

I thought its possible to use existing `menu` document and add this to `shop all` page content.

then reference each link to menu. I've done this but can't see it on the frontend am I forgetting to create component?


So, originally you've made the navigation in a dropdown I want to use that menu in de collection page.

I could also change the header, that way the menu stays in de header instead of page itself. Think this will only be a css thing?


And I was wondering, if you could guide me trough the logic etc in a call? I would pay your time ofcourse. I would like to hear from you

**Comment by ndimatteo** [comment]
No problem,

You'll need to create a new "module" and make sure you're including the data for it in the GROQ for your page modules.

1) You'd add this new module in Sanity here: https://github.com/ndimatteo/HULL/blob/main/studio/schemas/documents/shopify-collection.js#L34-L43
2) You'd include the new module in your GROQ here: https://github.com/ndimatteo/HULL/blob/main/data/queries.js#L156
_(likely something like `_type == 'inlineMenu'` or something)_
3) You'd create a new component and add it to the `switch` on the front-end here: https://github.com/ndimatteo/HULL/blob/main/components/modules/index.js#L21-L48

I'm not sure about your other question regarding the header. Appreciate the offer to pay for my guidance, but this is the most I can provide at this time due to my current bandwidth.

I'd suggest joining the Sanity Community slack and see if others can help you with building out custom modules like this if you're still having trouble! Best of luck 🤘
