### ISSUE TITLE
vimeo-loop recommendation 🎞  (AutoPlay dont work on first load if not muted.)

### ISSUE THREAD

**Issue by FRIKKern** [ndimatteo/HULL#75]
Hey! Thanks a lot for your wonderful public template.

I recommend to add "&muted=1" inside the vimeo url, so we can automatically play video on homepage.
This was a issue for me, so i wanted to notice you ✅

**Comment by ndimatteo** [comment]
Hey @FRIKKern thank you! 🙏 

That's interesting... according to the vimeo docs you shouldn't have to add that since `&background=1` mutes the video automatically for you: https://vimeo.zendesk.com/hc/en-us/articles/115011183028-Embed-background-and-chromeless-videos

> Adding this parameter will have the following effect: 
> 1. All player toggles and elements will be turned off (including the play/pause button!)
> 2. The video will automatically loop.
> 3. The video will be set to autoplay.
> 4. **The video will be muted.**

Nonetheless, I've added it for posterity. 🤘
