### ISSUE TITLE
Synchronization Doesn't Work Anymore

### ISSUE THREAD

**Issue by geniti** [ndimatteo/HULL#80]
When i add new products and edited them, they aren't sync to the studio. 

But when I change an image from an existing product in the studio and sync image to Shopify. This works properly.. 

Cannot find why or what is the problem here ..

Please help!!!

**Comment by ndimatteo** [comment]
Hey there @geniti 

Can you confirm that you have the following set up and working properly:

1. Webhooks are configured in Shopify _and_ they are pointing to **live URLs** (no localhost).
2. You've properly added all `.env` variables to your hosted environment (and deployed _after_ they were added)
3. Your API endpoints are triggering when a change is made in Shopify and there are no errors (check function logs)

And since this has come up before, please be sure that you **are not** using the [Sanity Connect plugin](https://apps.shopify.com/sanity-connect). HULL uses it's own custom sync functions, and does not use this plugin.

**Comment by geniti** [comment]
Hey @ndimatteo Thank for your response!

I think the problem was url from Vercel since they give 2 domains. 

I use the production domain now and its working again! 

is it true that images aren't sync from Shopify anymore? as this is something I see now

Again your starter is pretty amazing! (L)

**Comment by ndimatteo** [comment]
Glad to hear you were able to resolve it @geniti!

And images are not sync'd _from_ shopify _into_ Sanity. From a page data perspective (including images), HULL takes the approach that Sanity is the point of truth. It only sync's the necessary data from Shopify that's needed to create carts and checkouts.

However, HULL does include a custom Sanity "action" to sync images _from_ sanity _to_ Shopify, and this is simply to eliminate redundancy for having to upload images to Shopify for their secure checkout step (which loads the cart item images from Shopify).

I hope that helps clarify things, and good luck! 🤘

**Comment by hatzipanis** [comment]
> However, HULL does include a custom Sanity "action" to sync images from sanity to Shopify, and this is simply to eliminate redundancy for having to upload images to Shopify for their secure checkout step (which loads the cart item images from Shopify).

I have nothing to add here but to say that you've bloody thought of everything haven't you @ndimatteo.
