### ISSUE TITLE
Checkout page dont work

### ISSUE THREAD

**Issue by phikva** [ndimatteo/HULL#82]
Thanks for the awesome starter!

The products are showing up in the cart. But the checkout page is 404 page not found.
When I'm working from localhost it directs to the my -vercel.app/number/checkouts.

Not sure what I'm doing wrong here. New to this.

**Comment by ndimatteo** [comment]
hey there, glad you're digging the starter! 🤘 

As for checkouts, when clicking "Checkout" from the cart this just redirects to the shopify-hosted checkout page for that cart. It should not be taking you to a relative path on localhost or on Vercel.

The only customization that HULL offers regarding the checkout page, is specifying a custom domain (or sub-domain) to adjust this redirect to. This is only for those who've added a custom domain name to their **native shopify account**, which allows those checkout links to use your own domain instead of the `[store-name].myshopify.com` default.

This setting can be found in the HULL Sanity Studio under: "Settings" > "Shop" > **Shopify Store URL**

I'm guessing you added `[your-project-slug].vercel.app to this setting. This is not possible (that's where your headless storefront exists, which can't also be connected to Shopify native). This would explain the 404 page you're seeing– remember from above that the "Checkout" link is simply a redirect– as that page doesn't exist at your headless site.

I'd suggest either deleting that field in Sanity, or using a proper subdomain that's different than your headless storefront and making sure it's also setup properly in your native Shopify account.

Hope that helps, but let me know if anything needs clarified!

**Comment by phikva** [comment]
That made a lot of sense! Thank you for the help. It fixed it.
